Welcome: Welcome.

Intro: RSS Queue lets you quickly and easily create and curate RSS/podcast feeds that can be synchronized to your phone, tablet or computer. No registration is needed.

Instructions1h: Create a queue
Instructions1t: No registration needed. Just give your queue a name (“Funny cat videos”) and save the address.
Instructions2h: Add links
Instructions2t: Populate your new queue with links to videos or audio files you find on the net.
Instructions3h: Synchronize!
Instructions3t: Add the feed to your feed reader and live happily ever after. When you add new items they are automatically synced to your phone/tablet/computer.

CreateNewTitle: New RSS Queue
CreateNew: Create new queue →
Continue: Continue

QueueCreatedGreeting: Hi!
QueueCreatedText: This is your new queue. Please save this page's unique address, since you will need it to edit the queue later.
