################################################################################
# Home page
################################################################################

HomeWelcome: Welcome.
HomeIntro: RSS Queue lets you quickly and easily create and curate RSS/podcast feeds that can be synchronized to your phone, tablet or computer. No registration is needed.

HomeInstructions1h: Create a queue
HomeInstructions1t: No registration needed. Just give your queue a name (“Funny cat videos”) and save the address.
HomeInstructions2h: Add links
HomeInstructions2t: Populate your new queue with links to videos or audio files you find on the net.
HomeInstructions3h: Synchronize!
HomeInstructions3t: Add the feed to your feed reader and live happily ever after. When you add new items they are automatically synced to your phone/tablet/computer.

HomeCreateNew: New RSS Queue

################################################################################
# New page
################################################################################

NewCreateNewTitle: Create new queue
NewContinue: Continue

################################################################################
# Edit page
################################################################################

QueueAddToQueue: Add to queue
QueueCreatedGreeting: Hi!
QueueCreatedText1: This is your new queue.
QueueCreatedText2: Please save this page's unique address, since you will need it to edit the queue later.
QueueCreatedText3: Anyone with this address can edit your queue.
QueueCreatedText4: To add the feed to your podcast app or feed reader, use the feed link above. (Click on the help link in the menu if you are unsure about how to do this.) The read-only link allows people to see this page without being able to edit it.

################################################################################
# Feed info
################################################################################

FeedListRemove: Remove
FeedListNumItems count@Int: #{show count} #{plural count "item" "items"} in the queue

FeedInfoFeedLink: Feed link
FeedInfoFeedLinkHelp: The link you should add to your podcaster/feed reader. See the help page if you are unsure about how to do this.
FeedInfoReadOnlyLink: Read-only link
FeedInfoReadOnlyLinkHelp: Link to this queue that can be shared without giving people editing rights.

################################################################################
# Help page
################################################################################

HelpGettingStartedHeader: Getting Started
HelpGettingStartedText: After creating your own read/watch later queue you can fill it with content by providing a title and an address. You can add links to web pages or to media files. If you add your queue's feed url to a podcast app and you add direct links to audio or video files you will be able to download the files automatically to your phone or tablet as you add links. For links to web pages, all fead readers should work.
HelpPodcastAppsHeader: Podcast apps
HelpPodcastAppsText: Here are some podcast apps you can use to subscribe to your queue:
HelpAddingYourQueueHeader: Adding your queue to your podcast app
HelpAddingYourQueueText: On the top of your queue's page there is a feed link. This is the address that should be added to your podcast app. The way this is done varies form app to app. Some will let you specify an url directly while in other apps you will have to enter the address as a search term. To find out how this is done for your podcast app, please consult its documentation.
