Default: &defaults
  user: rssqueue
  password: rssqueue
  host: localhost
  port: 5432
  database: rssqueue
  poolsize: 10

Development:
  database: rssqueue_dev
  <<: *defaults

Testing:
  database: rssqueue_test
  <<: *defaults

Staging:
  database: rssqueue_staging
  poolsize: 100
  <<: *defaults

Production:
  poolsize: 100
  <<: *defaults
